WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Views/Player/Create.cshtml
WMBA-4/WMBA-4/Views/Player/Delete.cshtml
WMBA-4/WMBA-4/Views/Player/Details.cshtml
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml

Kim: Players

---

WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Views/Team/Create.cshtml
WMBA-4/WMBA-4/Views/Team/Delete.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/Edit.cshtml
WMBA-4/WMBA-4/Views/Team/Index.cshtml

add team controller and views

---

WMBA-4/WMBA-4/Controllers/DivisionsController.cs
WMBA-4/WMBA-4/Views/Divisions/Create.cshtml
WMBA-4/WMBA-4/Views/Divisions/Delete.cshtml
WMBA-4/WMBA-4/Views/Divisions/Details.cshtml
WMBA-4/WMBA-4/Views/Divisions/Edit.cshtml
WMBA-4/WMBA-4/Views/Divisions/Index.cshtml

here is the controller and views for divisions

---

WMBA-4/WMBA-4/Data/CommonCommands.txt

New Cooment on CommonCommands

---

WMBA-4/WMBA-4/Controllers/DivisionController.cs
WMBA-4/WMBA-4/Views/Division/Create.cshtml
WMBA-4/WMBA-4/Views/Division/Delete.cshtml
WMBA-4/WMBA-4/Views/Division/Details.cshtml
WMBA-4/WMBA-4/Views/Division/Edit.cshtml
WMBA-4/WMBA-4/Views/Division/Index.cshtml

new Division Controller

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

Seed Divisions Update

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Update Title, Update H1, Vista now show us word VS between Team1 Vs Team2, and date format

Improvements to Game Assigments

---

WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/Index.cshtml

Update Team controller, Team index view, Team Detail View, Layout file.

---

WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Views/Team/Details.cshtml

Updating Team Controller and Team Detail View

---

WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Shared/_LoginPartial.cshtml
WMBA-4/WMBA-4/wwwroot/css/Navigation.css
WMBA-4/WMBA-4/wwwroot/css/media.css
WMBA-4/WMBA-4/wwwroot/css/site.css
WMBA-4/WMBA-4/wwwroot/css/style.css
WMBA-4/WMBA-4/wwwroot/js/sidenav.js

Kim: Edit Layout

---

WMBA-4/WMBA-4/Views/Team/Details.cshtml

Teams Detail View Updated

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Controllers/GameLineUpController.cs
WMBA-4/WMBA-4/Views/Game/Details.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml
WMBA-4/WMBA-4/Views/GameLineUp/Create.cshtml
WMBA-4/WMBA-4/Views/GameLineUp/Index.cshtml

-- Cristina Added Line Up in the Index page of Games.

-- Cristina Added Line Up in the Index page of Games.

---

WMBA-4/WMBA-4/Controllers/ImportTeamController.cs
WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/_ImportTeam.cshtml

Created the importTeam controller and partial view I modified the the Intializer in the Seasons table -- I left just season 2023 and I edited all the tables related.

Cristina-- I added the LineUp option to the Details page in Teams.

---

WMBA-4/WMBA-4/Data/CommonCommands.txt

Add package for Excell files

---

WMBA-4/WMBA-4/Data/CommonCommands.txt

Git commands

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Controllers:
Game Controller
Views:
Views\Game\Create
Views\Game\Index

GameAssignments View Create New Match v1

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml

kim: Player controller, layout

kim: Player controller, layout

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

kim: for each team, added more players

kim: Initializer added

---

WMBA-4/WMBA-4/Views/Division/Index.cshtml

updated division index

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Data/WMBA_4_Context.cs
WMBA-4/WMBA-4/Models/Game.cs
WMBA-4/WMBA-4/Models/GameType.cs

Add gameTypes again, it was deleted by error previous delivery

Add gameTypes again, it was deleted by error previous delivery

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

FixingWMBA4InitializerSeed

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Delete.cshtml
WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Fixing Schedule Games Controller, back to

Fixing Schedule Games Controller, back to

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Models/Player.cs
WMBA-4/WMBA-4/Views/Home/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Create.cshtml
WMBA-4/WMBA-4/Views/Player/Delete.cshtml
WMBA-4/WMBA-4/Views/Player/Details.cshtml
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css
WMBA-4/WMBA-4/wwwroot/js/sidenav.js

Layouts
PlayerController
Player model

Initializer-edit MemberId

---

WMBA-4/WMBA-4/Views/Game/Details.cshtml

Change name of the link "back to Team List" to "back to Team Detail"

---

WMBA-4/WMBA-4/Controllers/HomeController.cs
WMBA-4/WMBA-4/Views/Home/Index.cshtml

select form gettting the count of Players, Games and Teaam on Dashboard.

Cristina -- added Game to dashboard and

---

WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Views/Team/Delete.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/Edit.cshtml
WMBA-4/WMBA-4/Views/Team/Index.cshtml

Team---In the Delete view put the name of the Team in the description - Modify buttons go list and edit and save

Team -- Copy dropdownList style from Kim (Players) -

---

WMBA-4/WMBA-4/Models/Team.cs

validations team edit

---

WMBA-4/WMBA-4/Controllers/DivisionController.cs
WMBA-4/WMBA-4/Views/Division/Create.cshtml
WMBA-4/WMBA-4/Views/Division/Details.cshtml
WMBA-4/WMBA-4/Views/Division/Edit.cshtml
WMBA-4/WMBA-4/Views/Division/Index.cshtml

Division update v2

---

WMBA-4/WMBA-4/Models/Team.cs

validation V2

---

WMBA-4/WMBA-4/Views/Game/Index.cshtml

Game Assignment Layout team1 vs team2

Game Assignment Layout team1 vs team2

---

WMBA-4/WMBA-4/Views/Game/Edit.cshtml

Game Assignment Edit buttons

---

WMBA-4/WMBA-4/Controllers/TeamController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Data/WMBA_4_Context.cs
WMBA-4/WMBA-4/Models/Role.cs
WMBA-4/WMBA-4/Models/Staff.cs
WMBA-4/WMBA-4/Models/Team.cs
WMBA-4/WMBA-4/Views/Team/Create.cshtml
WMBA-4/WMBA-4/Views/Team/Delete.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/Edit.cshtml
WMBA-4/WMBA-4/Views/Team/Index.cshtml

Can you please review if everything is correct?

-- I modified the Coah aproach in the Team section.

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Game Assignment Fixing Feedback prototype1

Game Assignment Fixing Feedback prototype1

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Edit.cshtml

Fix issues, same team team at the moment of Create and Edit

Fix issues, same team team at the moment of Create and Edit

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Data/WMBA_4_Context.cs
WMBA-4/WMBA-4/Models/Game.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml

Fix Game Assignments - Create Game, add create game by division

Fix Game Assignments - Create Game, add create game by division

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/ViewModels/GameEditVM.cs
WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Fix Game Assignments - Edit Game, add edit game by division

Fix Game Assignments - Edit Game, add edit game by division

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Data/WMBA_4_Context.cs
WMBA-4/WMBA-4/Models/Player.cs
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/wwwroot/js/checkbox.js

Kimlayoutwork

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml

Player-Edit view-duplicated division dropdown       
-Index view-duplicated column name
-Controller-Status update action

Player-Edit view-duplicated division dropdown

---

WMBA-4/WMBA-4/Controllers/HomeController.cs
WMBA-4/WMBA-4/Views/Home/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/wwwroot/css/style.css

Home View: Developed responsive layout, added cousel for game assignment
Player Index: Change active icon

Home View: Developed responsive layout, added cousel for game assignment

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Views/Game/Index.cshtml
WMBA-4/WMBA-4/wwwroot/css/style.css

Game Assignment - Index Sorting Indicator 
Add green arrows to indicate whether sorting is in ascending or descending order on the index page
Game Assignment - Index Filter Enhancement 
Include options to filter by Active and Inactive games on the index page
Game Assignment - Index Stylin
Apply different CSS styles to inactive rows on the index page to distinguish them visually

Fix Game Assignments - Several Fixes

---

WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/Shared/_InPlayPartial.cshtml

Is not orking yet properly, I am still working on it

-- I added the Inplay popup

---

WMBA-4/WMBA-4/Views/Home/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Delete.cshtml
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

Player: Edit - solved division

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Fix Game Assignments - Date Ordering correctly

Fix Game Assignments - Date Ordering correctly

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Fix Game Assignments - Index -  Year, Month and Day Filter has been added

Fix Game Assignments - Index -  Year,Month and Day Filter has been added

---

WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/ViewModels/InPlayMV.cs
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/Shared/_InPlayPartial.cshtml

Now you can manage the Hits,Runs and Outs
Also we can move the players between the bases
I added some validations too.

Cristina-- I added new functionality to Scorekeeping-

---

WMBA-4/WMBA-4/Controllers/DivisionController.cs
WMBA-4/WMBA-4/Controllers/StaffController.cs
WMBA-4/WMBA-4/Views/Division/Create.cshtml
WMBA-4/WMBA-4/Views/Division/Delete.cshtml
WMBA-4/WMBA-4/Views/Staff/Create.cshtml
WMBA-4/WMBA-4/Views/Staff/Delete.cshtml
WMBA-4/WMBA-4/Views/Staff/Details.cshtml
WMBA-4/WMBA-4/Views/Staff/Edit.cshtml
WMBA-4/WMBA-4/Views/Staff/Index.cshtml

edit staff and division

---

WMBA-4/WMBA-4/Views/ScorePlayer/Index.cshtml
WMBA-4/WMBA-4/wwwroot/css/style.css

Scorekeeper index: edit index design

---

WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml

Game Assignment - Index/Edit DropdownList

Game Assignment - Index/Edit DropdownList

---

WMBA-4/WMBA-4/Views/Staff/Index.cshtml

fix delete icon on staff index

---

WMBA-4/WMBA-4/Views/Division/Index.cshtml

fix delete division icon

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Views/Home/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Create.cshtml
WMBA-4/WMBA-4/Views/Player/Delete.cshtml
WMBA-4/WMBA-4/Views/Player/Details.cshtml
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Stats.cshtml
WMBA-4/WMBA-4/Views/Shared/_ImportTeams.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Team/ImportTeam.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

Player views: add pages navigations
Player detail: add stats

Home Index: add ability of touch slide on upcoming games

---

WMBA-4/WMBA-4/Controllers/DivisionController.cs
WMBA-4/WMBA-4/Controllers/StaffController.cs
WMBA-4/WMBA-4/Views/Staff/Index.cshtml

fix division and staff filter

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

ScorePlayer-filter count

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

Players - Desduplicate players on Seed Data

Players - Desduplicate players on Seed Data

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Views/ScorePlayer/Index.cshtml

solved sorting problem

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

Game - Create - Shorts Names on Teams in Seed data, and Create game with score=0

Game - Create - Shorts Names on Teams in Seed data, and Create game with score=0

---

WMBA-4/WMBA-4/Data/WMBA4Initializer.cs

Seed - Inicializer -  Locations (7 Memorial Parks Diamonds)
Memorial Park (Diamond 1)
Memorial Park (Diamond 2)
Memorial Park (Diamond 3)
Memorial Park (Diamond 4)
Memorial Park (Diamond 5)
Memorial Park (Diamond 6)
Memorial Park (Diamond 7)

Seed - Inicializer -  Locations (7 Memorial Parks Diamonds)

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/ViewModels/GameEditVM.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Game/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml

*Game Assignment - Edit Score Feature:
Enable the capability to record scores for the opposing team without allowing modifications to individual player stats.
*Game Assignment - Index Logo Removal:
Allow for the removal of logos on the games page as they are deemed distracting.
*Game Assignment - Index Score Calculation:
Investigate and clarify how runs for the opposing team are being added to the score on the index page.
*Seed Data Enhancement:
Consider using short names in the seed data for improved clarity and efficiency.
*Game Index Page Redesign:
Reformat the index page to match the navigation format used in the players section.
*Game Assignment/Edit Page Design:
Design the edit page to include a title providing information about the row being edited.
*Seed Data Initializer:
Include …

Game Assignment - Several Fixes

---

WMBA-4/WMBA-4/Views/Game/Index.cshtml

Display an edit view when a row is clicked in the Game Assignment index.

*Game Assignment - Index Edit View:

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Views/Player/Details.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml

ScoreKeeper: add innings but need to develop more. not working yet

Player: detail - stats improved, -index: improved

---

WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs

-- I fixed the Homerun functionality

---

WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Staff/Create.cshtml
WMBA-4/WMBA-4/Views/Staff/Delete.cshtml
WMBA-4/WMBA-4/Views/Staff/Details.cshtml
WMBA-4/WMBA-4/Views/Staff/Edit.cshtml
WMBA-4/WMBA-4/Views/Staff/Index.cshtml

tool tip on staff

---

WMBA-4/WMBA-4/Controllers/GameController.cs
WMBA-4/WMBA-4/Data/CommonCommands.txt
WMBA-4/WMBA-4/Views/Game/Index.cshtml

*Game Assignment - Index Edit View Fixes:
Correct the issue where editing changes the status from inactive to active.
Address responsiveness issues in the index layout.

*Game Assignment - Index Edit View Fixes:

---

WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

Keep working on Scorekeeper redesign. and css, and sidenavbar added Report menu

Keep working on Scorekeeper redesign. and css, and sidenavbar added Report menu

---

WMBA-4/WMBA-4/Controllers/EndSeasonController.cs
WMBA-4/WMBA-4/Data/ExtraMigration.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Data/WMBA_4_Context.cs
WMBA-4/WMBA-4/ViewModels/GameEndSeasonVM.cs
WMBA-4/WMBA-4/ViewModels/PlayerEndSeasonVM.cs
WMBA-4/WMBA-4/Views/EndSeason/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml

When the Admin decide to End season the system download a report of everything and truncate de tables I am just a judjusting the import file since is not working properly after end season.

--Developed End Season Feature.

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Views/Player/Delete.cshtml
WMBA-4/WMBA-4/Views/Player/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml
WMBA-4/WMBA-4/Views/Team/Create.cshtml
WMBA-4/WMBA-4/Views/Team/Delete.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml
WMBA-4/WMBA-4/Views/Team/Edit.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css

Player - changed team filter with division - team
Teams -  added navigation in Edit, Create, Details
CSS

Home - Login and menu for admin Player - changed team filter with division - team Teams -  added navigation in Edit, Create, Details CSS

---

WMBA-4/WMBA-4/Views/Game/Details.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/SelectTeam.cshtml

more tool tips

---

WMBA-4/WMBA-4/Controllers/PlayerController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Models/Division.cs
WMBA-4/WMBA-4/Views/Division/Create.cshtml
WMBA-4/WMBA-4/Views/Division/Delete.cshtml
WMBA-4/WMBA-4/Views/Division/Edit.cshtml
WMBA-4/WMBA-4/Views/Division/Index.cshtml
WMBA-4/WMBA-4/Views/Player/Create.cshtml
WMBA-4/WMBA-4/Views/Player/Edit.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/Team/Create.cshtml
WMBA-4/WMBA-4/Views/Team/Edit.cshtml

add navigation in all Division views
Add form-select class in team edit and create view

edit player's division selection include 1 division down. add navigation in all Division views Add form-select class in team edit and create view

---

WMBA-4/WMBA-4/Controllers/ReportController.cs
WMBA-4/WMBA-4/Views/Report/Index.cshtml
WMBA-4/WMBA-4/Views/Report/_GameReportPartial.cshtml
WMBA-4/WMBA-4/Views/Report/_PlayerReportPartial.cshtml
WMBA-4/WMBA-4/Views/Report/_TeamReportPartial.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml

Added tabs to report index
Create player, team, game partial views

Added Authorize for Report controller Added tabs to report index Create player, team, game partial views

---

WMBA-4/WMBA-4/Areas/Identity/Pages/Account/Login.cshtml
WMBA-4/WMBA-4/Program.cs
WMBA-4/WMBA-4/Views/Game/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_EnterPagePartial.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

CSS
Add Login page for first view page

Delete Add Team in Game index CSS Add Login page for first view page

---

WMBA-4/WMBA-4/Controllers/UserRoleController.cs

Prevent users from changing their own roles

Prevent users from changing their own roles

---

WMBA-4/WMBA-4/Controllers/HelpTopic.cs
WMBA-4/WMBA-4/Views/HelpTopic/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml

help topic page

---

WMBA-4/WMBA-4/Controllers/StaffController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Program.cs
WMBA-4/WMBA-4/Utilities/MakePassword.cs
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml

Hiding the user role managment
Sending emails when the admin change the role

Sending Emails when the admin create a user

---

WMBA-4/WMBA-4/Controllers/ReportController.cs
WMBA-4/WMBA-4/Models/Player.cs
WMBA-4/WMBA-4/ViewModels/PlayerStatsVM.cs
WMBA-4/WMBA-4/Views/Report/Index.cshtml
WMBA-4/WMBA-4/Views/Report/_PlayerReportPartial.cshtml
WMBA-4/WMBA-4/Views/Report/_TeamReportPartial.cshtml
WMBA-4/WMBA-4/Views/Team/Details.cshtml

-- Added select players for comparation

---

WMBA-4/WMBA-4/Controllers/ReportController.cs
WMBA-4/WMBA-4/Models/Team.cs
WMBA-4/WMBA-4/ViewModels/PlayerStatsVM.cs
WMBA-4/WMBA-4/Views/Report/PlayerStats.cshtml
WMBA-4/WMBA-4/Views/Report/TeamStats.cshtml

We can compare teams and players, also set rankings fro both

I modified the Reports secction.

---

WMBA-4/WMBA-4/Controllers/ReportController.cs
WMBA-4/WMBA-4/Controllers/StaffController.cs
WMBA-4/WMBA-4/Data/WMBA4Initializer.cs
WMBA-4/WMBA-4/Views/Report/PlayerStats.cshtml
WMBA-4/WMBA-4/Views/Report/TeamStats.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/Views/Shared/_Sidebar.cshtml
WMBA-4/WMBA-4/Views/Staff/Edit.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css
WMBA-4/WMBA-4/wwwroot/css/style.css

sidebar name chnaged report-add and edit

---

WMBA-4/WMBA-4/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/ForgotPassword.cshtml
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/Register.cshtml.cs
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml
WMBA-4/WMBA-4/Areas/Identity/Pages/Account/ResetPassword.cshtml
WMBA-4/WMBA-4/Controllers/ScorePlayerController.cs
WMBA-4/WMBA-4/Views/ScorePlayer/Index.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/ScoreKeeping.cshtml
WMBA-4/WMBA-4/wwwroot/css/layoutStyle.css

re design for identity pages. edit scorekeeper index

---

WMBA-4/WMBA-4/Controllers/HomeController.cs
WMBA-4/WMBA-4/Controllers/ReportController.cs
WMBA-4/WMBA-4/Views/Game/Create.cshtml
WMBA-4/WMBA-4/Views/Game/Edit.cshtml
WMBA-4/WMBA-4/Views/Home/Index.cshtml
WMBA-4/WMBA-4/Views/Report/PlayerRanking.cshtml
WMBA-4/WMBA-4/Views/Report/PlayerStats.cshtml
WMBA-4/WMBA-4/Views/Report/TeamRanking.cshtml
WMBA-4/WMBA-4/Views/Report/TeamStats.cshtml
WMBA-4/WMBA-4/Views/ScorePlayer/Index.cshtml
WMBA-4/WMBA-4/Views/Shared/_Layout.cshtml
WMBA-4/WMBA-4/Views/Shared/_PlayerRanking.cshtml
WMBA-4/WMBA-4/Views/Shared/_TeamRanking.cshtml
WMBA-4/WMBA-4/wwwroot/css/style.css

fix add location in game assaingment create
add back buttons in ranking page

add ranking pages in home index, fix add location in game assaingment create add back buttons in ranking page
